name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun i --frozen-lockfile
      - name: Lint, Check Format & Types
        run: bun run test
      - name: Build Project
        run: bun run build
